# Generated by Django 5.1.7 on 2025-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_payment_time_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_addon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
