# Generated by Django 5.1.7 on 2025-03-16 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_category_is_addon_item_is_available"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="826A425BD1", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ongoing", "进行中"),
                    ("Finished", "已完成"),
                    ("Canceled", "已取消"),
                ],
                default="Ongoing",
                max_length=20,
            ),
        ),
    ]
