# Generated by Django 5.1.7 on 2025-03-18 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_userprofile_phone_number_alter_order_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="merchant",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"is_merchant": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchant_orders",
                to="shop.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="5F7FDCDEE2", max_length=20, unique=True),
        ),
    ]
