# Generated by Django 5.1.7 on 2025-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_order_merchant_alter_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="618E20DA87", max_length=20, unique=True),
        ),
    ]
