# Generated by Django 5.1.7 on 2025-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_order_updated_at_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="2C48E4D62F", max_length=20, unique=True),
        ),
    ]
