# Generated by Django 5.1.7 on 2025-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_addon",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="addon_items",
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="CC1F1330B6", max_length=20, unique=True),
        ),
    ]
