# Generated by Django 5.1.7 on 2025-03-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="DCC4E7D92A", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.item"
            ),
        ),
    ]
