# Generated by Django 5.1.7 on 2025-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_orderitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="217BD5C22D", max_length=20, unique=True),
        ),
    ]
