# Generated by Django 5.1.7 on 2025-03-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_order_order_number_alter_orderitem_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_time",
        ),
        migrations.RemoveField(
            model_name="order",
            name="remark",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="373D377DA1", max_length=20, unique=True),
        ),
    ]
