# Generated by Django 5.1.7 on 2025-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_remove_order_payment_time_remove_order_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="8843F2676B", max_length=20, unique=True),
        ),
    ]
