# Generated by Django 5.1.7 on 2025-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="F1092D5937", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ongoing", "Ongoing"),
                    ("Finished", "Finished"),
                    ("Canceled", "Canceled"),
                ],
                default="Ongoing",
                max_length=20,
            ),
        ),
    ]
