# Generated by Django 5.1.7 on 2025-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_order_order_number_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="36A8A3F877", max_length=20, unique=True),
        ),
    ]
