# Generated by Django 5.1.7 on 2025-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="99DEEE495D", max_length=20, unique=True),
        ),
    ]
